all: p1a p1b p2a p2b

p1a: p1a.cpp
	g++ -pthread -o p1a p1a.cpp

p1b: p1b.cpp
	g++ -pthread -o p1b p1b.cpp

p2a: p2a.cpp
	g++ -pthread -o p2a p2a.cpp

p2b: p2b.cpp
	g++ -pthread -o p2b p2b.cpp

clean:
	rm p1a p1b p2