all: p1a p1b p1c p2a p2b p3

p1a: p1a.cpp
	g++ -o p1a -fopenmp p1a.cpp

p1b: p1b.cpp
	g++ -o p1b -fopenmp p1b.cpp

p1c: p1c.cpp
	g++ -o p1c -fopenmp p1c.cpp

p2a: p2a.cpp
	g++ -o p2a -fopenmp p2a.cpp

p2b: p2b.cpp
	g++ -o p2b -fopenmp p2b.cpp

p3: p3.cpp
	g++ -o p3 -fopenmp p3.cpp

clean:
	rm p1a p1b p1c p2a p2b p3